name: MCPlayNetwork wiki
baseurl: ""
url: ""
# Build settings
markdown: kramdown

social:
  Website: https://www.mcplay.biz
  Twitter: https://twitter.com/MCPlayNetwork
  YouTube: https://www.youtube.com/channel/UCCw30ZfwDq_czxcTofr_4LA
  GitHub: https://github.com/GravittoGroup/MCPlayNetwork-wiki/

nav:
  - title: トップページ
    url: /
  - title: サーバー
    dropdown:
      - title: Hub
        url: /servers/Hub/
      - title: Survival
        url: /servers/Survival/
      - title: Creative
        url: /servers/Creative/
      - title: VillageDefense
        url: /servers/VillageDefense/
      - title: MissileWars
        url: /servers/MissileWars/
      - title: AncientRPG
        url: /servers/AncientRPG/