name: MCPlayNetwork wiki
baseurl: ""
url: ""
# Build settings
markdown: kramdown

social:
  Website: https://www.mcplay.biz
  Twitter: https://twitter.com/MCPlayNetwork
  YouTube: https://www.youtube.com/channel/UCCw30ZfwDq_czxcTofr_4LA
  GitHub: https://github.com/GravittoGroup/MCPlayNetwork-wiki/

nav:
  - title: Home
    url: /
  - title: item 1
    dropdown:
      - title: item 1
        url: /#
      - title: item 2
        url: /#
      - title: item 3
        url: /#
      - title: item 4
        url: /#
