name: MCPlayNetwork wiki
baseurl: ""
url: ""
# Build settings
markdown: kramdown

social:
  Website: https://www.mcplay.biz
  Twitter: https://twitter.com/MCPlayNetwork
  YouTube: https://www.youtube.com/channel/UCCw30ZfwDq_czxcTofr_4LA
  GitHub: https://github.com/GravittoGroup/MCPlayNetwork-wiki/

nav:
  - title: トップページ
    url: /
  - title: ガイドライン
    dropdown:
      - title: ゲーム内ガイドライン
        url: /InGameGuideline.html
      - title: コミュニティガイドライン
        url: /CommunityGuideline.html
      - title: 異議申し立て
        url: /AppealPunishment.html
  - title: サーバー
    dropdown:
      - title: Hub
        url: /servers/Hub/
      - title: Survival
        url: /servers/Survival/
      - title: Creative
        url: /servers/Creative/
      - title: VillageDefense
        url: /servers/VillageDefense/
      - title: AncientRPG
        url: /servers/AncientRPG/

