site_name: MCPlayDocs
site_description: 'MCPlayに属するプロジェクトのドキュメント'
site_author: 'GravittoGroup, MCPlay Team'
site_url: 'https://wiki.mcplay.biz/'
repo_name: 'gravitto/MCPlayDocs'
repo_url: 'https://github.com/gravitto/MCPlayDocs'
theme:
  name: 'material'
  language: 'ja'
  custom_dir: 'custom'
  palette:
    primary: 'Blue Grey'
    accent: 'Blue Grey'
  feature:
    tabs: true
extra:
  search:
    language: 'ja'
markdown_extensions:
    - admonition
nav:
    - ホーム: index.md
    - サーバー:
      - 概要: server/index.md
      - ハブ:
        - 仕様: server/Hub/index.md
      - サバイバル:
        - 仕様: server/Survival/index.md
        - ワールド: server/Survival/world.md
        - 追加要素:
          - mcMMO: server/Survival/Extension/mcMMO.md
      - クリエイティブ:
        - 仕様: server/Creative/index.md
    - パッチノート:
        - パッチノートについて: patch/index.md
        - Minecraft:
          - 8.3.xパッチノート: patch/Minecraft/8.3.x.md
        - Web:
          - パッチノート: patch/Web/index.md
        - Discord:
          - パッチノート: patch/Discord/index.md
