site_name: MCPlayWiki
site_description: 'MCPlayに属するプロジェクトのドキュメント'
site_author: 'GravittoGroup, MCPlay Team'
site_url: 'https://wiki.mcplay.biz/'
repo_name: 'mcplay/wiki'
repo_url: 'https://github.com/mcplay/wiki'
theme:
  name: 'material'
  language: 'ja'
  custom_dir: 'custom'
  palette:
    primary: 'Blue Grey'
    accent: 'Blue Grey'
  feature:
    tabs: true
extra:
  search:
    language: 'ja'
markdown_extensions:
    - admonition
nav:
    - ホーム: index.md
    - サバイバル:
      - 仕様: Survival/index.md
      - ワールド: Survival/world.md
      - 追加要素:
        - mcMMO: Survival/Extension/mcMMO.md
