site_name: MCPlayHelp
site_description: 'MCPlay Help website'
site_author: 'GravittoGroup, MCPlay Team'
site_url: 'https://wiki.mcplay.biz/'
repo_name: 'mcplay/wiki'
repo_url: 'https://github.com/mcplay/wiki'
theme:
  name: 'material'
  language: 'ja'
  custom_dir: 'custom'
  palette:
    primary: 'Blue Grey'
    accent: 'Blue Grey'
  feature:
    tabs: true
extra:
  search:
    language: 'ja'
  social:
    - type: 'github'
      link: 'https://github.com/mcplay'
    - type: 'twitter'
      link: 'https://twitter.com/MCPlayNetwork'
markdown_extensions:
    - admonition
nav:
  - ホーム: index.md
  - サバイバル:
    - サバイバルについて: Survival/index.md
    - GriefPrevention: Survival/GriefPrevention.md
    - mcMMO: Survival/mcMMO.md
