site_name: MCPlay wiki
theme:
  name: 'material'
  language: 'ja'
  custom_dir: 'custom'
  palette:
    primary: 'Blue Grey'
    accent: 'Blue Grey'
  feature:
    tabs: true
extra:
  search:
    language: 'ja'
